CM-420: developed new upload flow with validation
openimis/openimis-be-social_protection_py pull request #45
Opened 2024-01-09 15:02 UTC by sniedzielski

TICKET: https://openimis.atlassian.net/browse/CM-420

2024-01-10 09:11 UTC, delcroip requested changes
Please add unit test for the service (direct or through API)

2024-01-19 16:33 UTC, dborowiecki requested changes
I left two comments. Also please add tests in order to enhance coverage and pass quality gateway

2024-01-19 16:33 UTC, dborowiecki commented on social_protection/services.py
> +            percentage_of_invalid_items = (invalid_items / total_items) * 100
I think that both items are integers and in that case output will always be 0.

2024-01-19 16:33 UTC, dborowiecki commented on social_protection/services.py
> +            invalid_items = len(self.__fetch_summary_of_broken_items(upload_id))
Your calling `.__fetch_summary_of_broken_items` twice in this method. Could you do it once in order to improve performance?

2024-01-19 19:33 UTC, sniedzielski commented
I added some basic test to check if the most important services works without raising any errors. I'll extend those tests later while developing another features.

2024-01-23 08:35 UTC, dborowiecki approved these changes

2024-01-23 08:35 UTC, merged